#!/usr/bin/env python

from debian.deb822 import Changes
from email.parser import Parser
import subprocess
import json
import sys
import re
import os

from fred import db


p = Parser()
email = p.parse(sys.stdin)

content = email.get_payload()

changes = Changes(content)
source, version, dist = (changes[x] for x in (
    'Source', 'Version', 'Distribution'))


if not source.startswith("python-"):
    sys.exit(0)


db.builds.insert({
    "_id": "%s/%s" % (source, version),  # prevent dupes
    "source": source,
    "version": version,
    "dist": dist
}, safe=True)
